### ISSUE TITLE
URIs for instances with labels

### ISSUE THREAD

**Issue by natuk** [cpetrakis/RDFVisualizer-webapp#1]
Hello, and thank you for the great work with the RDFVisualizer. I have a feature request:

The URIs for instances with `rdfs:label` are hidden. It would be very helpful if the URI was shown for these instances as a tooltip (i.e. after hovering above the label). A user case for this is during CRM mapping when the user wants to test both the label and the rules for the production of URIs - typically from the *3M instance generator*.

**Comment by cpetrakis** [comment]
Hi @natuk and thanks for the feedback,

I think that a part of your requested feature already exists :)
If you right-click on an instance, the following context menu will appear: 

![copy uri2](https://user-images.githubusercontent.com/17297420/34666429-138597ca-f46d-11e7-98b1-2f4bc33f0490.png)


As you see this menu offers three functionalities:
- Opens the URI of selected item in new tab in the browser
- Copies the URI of selected item
- Shows the path of selected item in a modal

Is that enough or would you prefer to see the uri on mouseover to avoid the copy-paste clicks?
Either way this is an interesting feature i will keep in mind for future improvement!

**Comment by natuk** [comment]
I had no idea about this. This indeed allows the URI to be inspected but it requires a couple of extra requests. I think triggering a tooltip on mouseover may still be useful. Maybe see if anyone else would also find it useful. Thanks again.

**Comment by cpetrakis** [comment]
I understand that a mousover tooltip would be a ‘clicksaver’ and simplify the process of testing you describe above, so I’m seriously considering of adding your feature to a next version of the tool :) 
Thanks!

**Comment by cpetrakis** [comment]
Hi @natuk i think the requested feature is ready!

Here is a screenshot: 

![untitled](https://user-images.githubusercontent.com/17297420/42313864-6637c248-804c-11e8-8dd5-ae7f48f23fc0.png)

A mousover tooltip has been added to the tool so you can inspect the uri of the chosen entity.

**Comment by natuk** [comment]
Fantastic! This will save a lot of time. Thank you very much. I will look for it on FORTH's 3M instance with the new update.
